site_name: CollabPlatform — Лабораторная работа 1
site_description: Документация к серверному приложению платформы поиска партнёров для проектов
theme:
  name: material
  language: ru
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy

nav:
  - Главная: index.md
  - Установка: setup.md
  - Модель данных: models.md
  - API: api.md
  - Авторизация: auth.md
  - Практики: practices.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true
